// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhfmxvkiviqqmkebhakl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZm14dmtpdmlxcW1rZWJoYWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTE3ODYsImV4cCI6MjA3MjE2Nzc4Nn0.zKYqOv1qd-7B6pvzzRnqIu-adZ7PNjDRmpRhZKGa6f0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});